### ISSUE TITLE
Model folder path issues

### ISSUE THREAD

**Issue by MetinSeven** [n00mkrad/cupscale#1]
Hi @n00mkrad ,

In the latest Cupscale version I can't seem to enter a new model path.

1. After pasting a path and closing the Options dialog, the old model folder is still used.
2. When I open the options again, the model input field turns out to be empty.

After that I moved all of my ESRGAN models to one folder (folder name without spaces, just to make the path extra valid).
Now Cupscale crashes after entering the new path and trying to open the models dialog.

Looking at the crash error details, Cupscale still tries to locate the old, deleted folder.

In the end I've manually updated the path in the config.ini file, and now it works.

**Comment by n00mkrad** [comment]
Should be fixed already, re-download the latest release.
Will reopen if the issue persists.
