### ISSUE TITLE
Black square when upscaling with ESRGAN pytorch

### ISSUE THREAD

**Issue by Blazeolmo** [n00mkrad/cupscale#108]
https://youtu.be/_5etxopUX-0
 i have no idea how to do stuff
I'm using the 4x_minepack model but it does that with every model while using pytorch mode. i'm using a 1660 super with the latest drivers and cuda thingy.
![Screenshot (54)](https://user-images.githubusercontent.com/85788260/152222714-50d8231f-ad81-48d2-8ec9-7e7be9b3590c.png)
t

**Comment by Garux** [comment]
Disabling `Half Precision` defaulted option helped me with this.

**Comment by Blazeolmo** [comment]
> Disabling `Half Precision` defaulted option helped me with this.

thanks! it worked for me!
