### ISSUE TITLE
How to disable GPU in Windows 10?

### ISSUE THREAD

**Issue by zydjohnHotmail** [n00mkrad/cupscale#133]
Hello:
I want to use your repo for upscale some videos (mp4 format).  But I don't have usable GPU.  For all those Python package using GPU, it simply not work.
However, my PC has 32-core CPU, so I think my CPU is powerful enough to run the program.
Please advise on how to disable GPU and run the program only on CPU.
I am using Windows 10 (Version 21H2) and my IDE is Visual Studio 2022 (Version 17.2.3).
Thanks,

**Comment by Katzenwerfer** [comment]
Both PyTorch and NCNN backends can be forced to run on CPU.
For NCNN, just set the GPU id to -1 in the Cupscale settings.
In the case of PyTorch, you would need to install python in your system with all the required dependencies. PyTorch needs to be installed for use with CPU only.
In general, don't expect it to run any fast, even on your processor. CPU inference is slow in general.

**Comment by zydjohnHotmail** [comment]
Thanks!
