### ISSUE TITLE
Need some advice on which models to use.

### ISSUE THREAD

**Issue by zydjohnHotmail** [n00mkrad/cupscale#134]
Hello:
I want to upscale some videos (in MP4 format), most of those videos have low resolution, like: 640x480.  If I want to upscale them to at least 720P (1280x720), then which models I should download?  I am using C# on Windows 10.
I searched the following 3 pages:
1) https://upscale.wiki/wiki/Model_Database
This page has too many different models, which ones can meet my requirement?
2) https://nmkd.de/?esrgan-list
I got 404 error:
What you are looking for doesn't exist anymore or has never existed.
Make sure there are no typos in the address.
3) For discord, I try to know how to find useful information from it now.
Therefore, now I can only look for model from the first web page.
But due to the high number of models available, please advise on which one best fit my needs.
Thanks,

**Comment by n00mkrad** [comment]
1) Try them

2) Correct link is https://nmkd.de/?esrgan

You have not mentioned what you want to achieve so I can't tell you which models are best lol
