### ISSUE TITLE
Nvidia A100 GPU on Windows Server 2022 - GPU not detected

### ISSUE THREAD

**Issue by dustyny** [n00mkrad/cupscale#152]
From what I can see CUDA is installed properly and it's visible from within python (testing using torch). I'm not sure why Cupscale isn't detected it..

**Comment by grexzen** [comment]
Because you need to tweak torch to work with the A100.

**Comment by dustyny** [comment]
Ah that makes sense.. I forgot that different GPU types need to be supported specifically.
