### ISSUE TITLE
Error: Can't find upscaled output image! 

### ISSUE THREAD

**Issue by amauryjaphet** [n00mkrad/cupscale#157]
I used the ESRGAN (Pytorch edition) ai  and this happened:
Error: Can't find upscaled output image! This probably means the AI implementation failed to run correctly.

Index outside the bounds of the array.

Stack Trace:
   in Cupscale.Main.Upscale.GetOutputImg()

pls help im crying right now aaaaaaaaaaaaaaaaaaaa

**Comment by paddymccallan** [comment]
I changed my AI network to Real-ESRGAN as opposed to ESRGAN (Pytorch) - this seems to work for me.. Not sure if its the exact same issue I was facing with ESRGAN (Pytorch) but its seemingly looking for the output image in CupScaleData - heres my stack trace >

```
Error during FilenamePostprocess(): 

Could not find file 'C:\Users\abc\Downloads\Cupscale.1.39.0f1\Cupscale 1.39.0f1\CupscaleData\img-out\img-8iiMAjGwrbN6MCK7vWa8791K.png'.

Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)

   at Cupscale.Main.Upscale.FilenamePostprocess(String file)

```

**Comment by amauryjaphet** [comment]
ok let me try

**Comment by amauryjaphet** [comment]
i think i need to close this issue to close as not planned
