### ISSUE TITLE
Lockup after installing embedded python

### ISSUE THREAD

**Issue by Tanks404** [n00mkrad/cupscale#24]
Tested with 1.36.0. After compression is completed and the embedded python text box reads "Done!" program does not allow you to close out of the window. Terminating CupScale in task manager and reopening presents an unhandled exception showing the following file is missing: "\Cupscale1.36.0\Cupscale1.36.0\CupscaleData\ShippedEsrgan\esrlupscale.py". CupScale remains useable, but error continues to present itself anytime settings is entered and then closed. 

See below for full exception text:

************** Exception Text **************
System.IO.FileNotFoundException: Could not find file 'C:\Users\USER\Downloads\Cupscale1.36.0\Cupscale1.36.0\CupscaleData\ShippedEsrgan\esrlupscale.py'.
File name: 'C:\Users\USER\Downloads\Cupscale1.36.0\Cupscale1.36.0\CupscaleData\ShippedEsrgan\esrlupscale.py'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Cupscale.OS.EmbeddedPython.<Init>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Cupscale.Forms.SettingsForm.<SettingsForm_FormClosing>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4311.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Cupscale
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/Cupscale1.36.0/Cupscale1.36.0/Cupscale.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4311.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Magick.NET.Core
    Assembly Version: 6.1.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/Cupscale1.36.0/Cupscale1.36.0/Cupscale.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4290.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Magick.NET-Q16-AnyCPU
    Assembly Version: 7.23.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/Cupscale1.36.0/Cupscale1.36.0/Cupscale.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Cyotek.Windows.Forms.ImageBox
    Assembly Version: 1.2.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/Cupscale1.36.0/Cupscale1.36.0/Cupscale.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
HTAlt WinForms
    Assembly Version: 0.1.6.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/Cupscale1.36.0/Cupscale1.36.0/Cupscale.exe
----------------------------------------
HTAlt.Standart
    Assembly Version: 0.1.6.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/Cupscale1.36.0/Cupscale1.36.0/Cupscale.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 4.0.0.1
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/Cupscale1.36.0/Cupscale1.36.0/Cupscale.exe
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.4.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/Cupscale1.36.0/Cupscale1.36.0/Cupscale.exe
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.4.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/Cupscale1.36.0/Cupscale1.36.0/Cupscale.exe
----------------------------------------
PaintDotNet.Base
    Assembly Version: 3.36.7079.22820
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/Cupscale1.36.0/Cupscale1.36.0/Cupscale.exe
----------------------------------------
DdsFileTypePlus
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/Cupscale1.36.0/Cupscale1.36.0/Cupscale.exe
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Cyotek.Windows.Forms.TabList
    Assembly Version: 2.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/Cupscale1.36.0/Cupscale1.36.0/Cupscale.exe
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
NvAPIWrapper
    Assembly Version: 0.8.1.100
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/USER/Downloads/Cupscale1.36.0/Cupscale1.36.0/Cupscale.exe
----------------------------------------

**Comment by n00mkrad** [comment]
Found the problem, will be fixed in the next release (a hotfix likely dropping later today).

**Comment by Tanks404** [comment]
Works great! Appreciate your work!
