### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by igor-kurenkov** [n00mkrad/cupscale#35]
Hi. Tried to move it to C:/Program Files. Tried to manually make Cupscale folder in %APPDATA%. Tried -portable, gives me Error saying that another instance of Cupscale is running wich is not true. Starts well from the same folder accessed by another PC in a local network. The sessionlog.txt only says 
5-6-2021 10:11:34: Arg: C:\Program Files\Cupscale1.37.0\Cupscale.exe
Is there any way to turn on verbose mode or see detailed logs?

**Comment by n00mkrad** [comment]
Please don't put it into Program Files.

**Comment by igor-kurenkov** [comment]
Thank you, it didn't work from any location. I had to reinstall Windows, now it runs.
