### ISSUE TITLE
Request: Google Colab implementation.

### ISSUE THREAD

**Issue by ericstheguy** [n00mkrad/cupscale#40]
Is there a possibility for a _colab notebook_ port, with all the main features of cupscale built-in? (Including Video / Image upscale. CUDA processing, compatibility with many models, Interpolation of models etcetera.) 
Would be a _useful and_ **faster** alternative to _AMD/Intel_ computers limited to _CPU or NCNN_.

**Comment by Katzenwerfer** [comment]
There is already a notebook with most features of Joey's ESRGAN fork
https://github.com/styler00dollar/Colab-ESRGAN

**Comment by ericstheguy** [comment]
> There is already a notebook with most, if not all the features of Joey's ESRGAN fork
> https://github.com/styler00dollar/Colab-ESRGAN

Thanks, literally thought I'd already been through all available notebooks.
