### ISSUE TITLE
Is it possible to add multithreaded image processing? 

### ISSUE THREAD

**Issue by GiRaFa-SM** [n00mkrad/cupscale#5]
Some forks of W2X have multithreading added for images which makes GPU usage 100% all the time. One of the GPUs i had stopped working because i made large batch upscales and it made GPU usage go from 0 to 100 in seconds, which ruined its VRMs in a long term. (it seems the program is running 2 or more threads of the same executable, and also, im using a AMD GPU now)

Also, when using some models, they upscales to 4x or more, some models do include in their names what they`ll do, but at this point, is it possible to add custom resolutions? Sometimes i do not need a 7000x4000 image as 3700x2700 is enough for some needs. (or i may be missing something, though the resize options apparently do not do anything)

**Comment by Katzenwerfer** [comment]
About the second part, it's not possible since models are pre-trained with the upscale factor already.
Only way would be to train the same data into a lower upscale factor dataset

**Comment by Katzenwerfer** [comment]
And the resize is a post-processing thing

**Comment by n00mkrad** [comment]
With improved tiling code in an upcoming update, GPU load is always close to 100%.

ESRGAN does currently not support scale-less models, you can only upscale to the scale the model was trained on.
