### ISSUE TITLE
Downloads Models every launch?  Also is freezing after launch.

### ISSUE THREAD

**Issue by Ghee36** [n00mkrad/cupscale#54]
Running as administrator didn't solve this issue.  It install prerequisites and models after every launch and once its done it is just a frozen UI that makes the OS/explorer bloop noise as an error whenever anything is clicked as the program hangs.

**Comment by Ghee36** [comment]
It is working now after letting it hang for about 20 minutes, now starts up without issue.  Were the models downloaded or do I have to download them and put them in the models folder?  Because its empty.

**Comment by Ghee36** [comment]
Cool!  This GUI is wonderful and a boon to those with sucky motor control.  Is there a recommended list of models and their download locations?

**Comment by n00mkrad** [comment]
You can get ESRGAN models from the following sources:

1) The GameUpscale Wiki: https://upscale.wiki/wiki/Model_Database
2) NMKD's Website: https://nmkd.de/?esrgan-list
3) The GameUpscale Discord: https://discord.gg/nbB4A5F (#model-releases)
