### ISSUE TITLE
Enhancement:  up sample an image for X2 scale, with X4 model

### ISSUE THREAD

**Issue by Gamer4Life2020** [n00mkrad/cupscale#67]
Be able to up sample an image for X2 scale, with X4 model like Real-ESRGAN --outscale 2

**Comment by Katzenwerfer** [comment]
An easier solution is to just downscale the output

**Comment by n00mkrad** [comment]
Set "resize after upscaling" to 50%.

This is the same thing Real-ESRGAN does, except I don't use Lanczos (which I could add).
