### ISSUE TITLE
Adware or false positive? 

### ISSUE THREAD

**Issue by DvST8x** [n00mkrad/cupscale#69]
Cupscale.1.38.0f1.zip

BScope.Adware.Presenoker
Dropper.Agent.Win32.461664

https://www.virustotal.com/gui/file/f70f7a84c5984612776ee8d40635a8bae283650049d478c8c49d059ade12b30a/detection

**Comment by n00mkrad** [comment]
False positive.

Ever heard of the Antivirus Zillya VBA32? Yeah me neither.
