### ISSUE TITLE
windowed mode

### ISSUE THREAD

**Issue by Isgarh** [n00mkrad/cupscale#70]
hey there. is there a way to make it so Cupscale GUI starts in windowed mode (not maximized) ? I've looked in Cupscale Settings and found nothing to change this behavior. Whenever I first open Cupscale, it opens up maximized. I can get it out of the maximized mode after opening it, but I would prefer if it didn't start maximized - or if there was a setting to choose between starting in a smaller windowed mode or maximized... but I didn't find a setting for this. Thanks for making this tool btw. I started using it very recently and really like it overall

**Comment by n00mkrad** [comment]
Will be in next update

https://github.com/n00mkrad/cupscale/commit/1cf361efecc385148698dfb027f016a87cee597e
