### ISSUE TITLE
Humble request

### ISSUE THREAD

**Issue by sirciro** [n00mkrad/cupscale#76]
Please dear good sir, could you please make a linux version available, of course if you are willing to do so generously.

Or perhaps a version that can run on Wine.

Thank you in advance

**Comment by n00mkrad** [comment]
Not happening, most Linux users prefer command line anyway.

**Comment by Xeddius** [comment]
I've been a happy Linux sysadmin for more than 10 years now and I can say with confidence having the ability to rapidly preview, drag-and-drop, and interpolate models without mountains of typing or creating 20 bash scripts is by far an improvement in workflow. I understand your reluctance to even attempt this but to immediately dismiss the concept with a statement about "most" Linux users is a faulty generalization and an informal fallacy. I would throw money towards the goal of a working interface for linux or at least some method for getting it functional in wine. I dislike dual-booting and as you know Virtualization just doesn't suffice in this case. Not to mention numerous dependency issues with ESRGAN depending on the linux distribution you use, having something consistent would be much better.

**Comment by BuyMyMojo** [comment]
NCNN produces this error under wine
![image](https://user-images.githubusercontent.com/46948241/138253593-8adc3392-ca1e-4f44-b80c-86744e6ac1d0.png)

But the Pytorch does work but only in CPU mode which is obviously much slower.

When trying upscale in GPU mode it throws this error
```
[CMD] /C cd /D "Z:\home\buymymojo\Cupscale 1.39.0f1\CupscaleData\bin\esrgan-pyto
rch" & "Z:\home\buymymojo\Cupscale 1.39.0f1\CupscaleData\bin\py\python.exe" upsc
ale.py --input "Z:\home\buymymojo\Cupscale 1.39.0f1\CupscaleData\preview" --outp
ut "Z:\home\buymymojo\Cupscale 1.39.0f1\CupscaleData\preview-out"   --device_id 
0   --alpha_mode 1   "Z:\home\buymymojo\Cupscale 1.39.0f1\CupscaleData\models\ES
RGAN\Generic\4x_NMKD-Superscale-SP_178000_G.pth"
[Python] Traceback (most recent call last):
[Python]   File "upscale.py", line 11, in <module>
[Python]     import torch
[Python]   File "Z:\home\buymymojo\Cupscale 1.39.0f1\CupscaleData\bin\py\Lib\sit
e-packages\torch\__init__.py", line 116, in <module>
[Python]     raise err
[Python] OSError: [WinError -529697949] <no description> Error loading "Z:\home\
buymymojo\Cupscale 1.39.0f1\CupscaleData\bin\py\Lib\site-packages\torch\lib\torc
h_python.dll" or one of its dependencies.
[ESRGAN] Upscaling Error: Index was outside the bounds of the array.
  at Cupscale.Main.Upscale.Run (System.String inpath, System.String outpath, Cup
scale.Data.ModelData mdl, System.Boolean cacheSplitDepth, System.Boolean alpha, 
Cupscale.UI.PreviewUi+PreviewMode mode, System.Boolean showTileProgress) [0x0040
d] in <263174a4b4a54bd7b0ce2696f5fa92f2>:0
```


Another issue unrelated to the actual upscale process in zooming and panning around an image is slower under wine compared to native windows. a native linux version of cupscale would be much appreciated and more useful then just a CMD program. no other software lets you preview the scale on a small chunk of the image before scaling the full image.

**Comment by michael-conrad** [comment]
any hope for this? I generally do not do CLI if I an avoid it. And really don't know how to CLI this stuff anyways.

**Comment by BuyMyMojo** [comment]
> any hope for this? I generally do not do CLI if I an avoid it. And really don't know how to CLI this stuff anyways.

To do this in Cli I use to the same fork of ESRGAN that cupscale is based off which just uses python, it works but doesn't let you just do parts of the image easily to test like cupscale does

https://github.com/JoeyBallentine/ESRGAN

**Comment by maplepy** [comment]
@michael-conrad nope
