### ISSUE TITLE
Embedded Python problem

### ISSUE THREAD

**Issue by Iftuga** [n00mkrad/cupscale#8]
I tried this tool with system python, and it worked great. Next thing, I wanted to test it with the "-portable" argument and embedded python. In this configuration tool gets stuck every time at "Upscaling..." status. There are no errors in GUI, but after I enabled  "Show CMD Windows" in the debug settings, I got this:
```
D:\Programs\Cupscale\CupscaleData\ShippedEsrgan\py\Lib\site-packages\torch\cuda\__init__.py:125: UserWarning:
GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
```
I believe there is a problem with an old version of PyTorch in embedded python, but I am not sure.

**Comment by n00mkrad** [comment]
Embedded Python does currently not support RTX 3000 GPUs.

https://github.com/n00mkrad/flowframes/blob/main/PythonDependencies.md
