### ISSUE TITLE
Big images crashes my pc (cpu)

### ISSUE THREAD

**Issue by starinspace** [n00mkrad/cupscale#80]
I do not have a nvidea-card so its only gpu that works. Wierdly, small images does work as long as I do them one by one but not by batch and not bigger images. Sometimes even small images does make my pc crash, first the mouse get frozen, then the screen gets black. I get no error messages at all. All drivers are up to date as well through the *Auto-Detect and Install Updates for Radeon™ Graphics and Ryzen™ Chipset Drivers for Windows®*

I have a CPU **AMD A10-7800 Radeon R7, 12 Compute Cores 4C+8G**, I do have GPU **AMD Raden(TM) R7 Graphics** (but thats not supported).

**Comment by n00mkrad** [comment]
Your GPU is simply to old and weak for anything serious.

**Comment by starinspace** [comment]
Do you meen GPU or CPU?
