### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DillFrescott** [n00mkrad/cupscale#84]
So with ffmpeg there is the option to set "cpu time" where if you set it super low, the computer spends a ton more time per frame, but you get really good detail and quality.

Is there an equivalent in cupscale? I'd be fine with it taking a few hours to upscale an image if the results would be even better than they already are.

**Comment by n00mkrad** [comment]
For upscaling? There's TTA which takes 5-8x as long, it barely improves quality thought. It's only compatible with the NCNN implementations. You can enable it in the settings.

**Comment by DillFrescott** [comment]
@n00mkrad Ah, gotcha. There is no other value? To make the computer spend more time and resources on perfecting the image/frame?

By the way this software is great! Thank you so much! :)
