### ISSUE TITLE
Error with pytorch

### ISSUE THREAD

**Issue by DillFrescott** [n00mkrad/cupscale#85]
Error: Can't find upscaled output image! This probably means the AI implementation failed to run correctly.

Index was outside the bounds of the array.

Stack Trace:
   at Cupscale.Main.Upscale.GetOutputImg()

--------------------------
Error during FilenamePostprocess(): 

File name cannot be null.

Parameter name: sourceFileName

Stack Trace:
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)

   at Cupscale.Main.Upscale.FilenamePostprocess(String file)

The error message was copied to the clipboard.

**Comment by DillFrescott** [comment]
Nevermind I figured it out

**Comment by Sidiusz** [comment]
so what's the solution?

**Comment by DillFrescott** [comment]
> so what's the solution?

You need to select a different method on the left hand side drop down

**Comment by DillFrescott** [comment]
I'm not at the computer currently so I forgot the name of it

**Comment by Flecser** [comment]
> I'm not at the computer currently so I forgot the name of it

can you please explain more on what this "different method" means?? and if you can please send me a screen shot because I am lost. and I don't know what I am doing.

**Comment by DillFrescott** [comment]
https://i.imgur.com/vXF7haQ.png

**Comment by Flecser** [comment]
> https://i.imgur.com/vXF7haQ.png

I tried all 3 methods but its giving me the same errors for all of them.

**Comment by DillFrescott** [comment]
Last time I tested it, it was on an older version. Perhaps the new update broke all of the methods... :/

**Comment by Flecser** [comment]
can you tell me which version worked for you?

**Comment by DillFrescott** [comment]
Sh sorry, I was wrong, I thought there was an update sooner than September. Do you have an Nvidia GPU?

**Comment by Flecser** [comment]
No I am using my cpu, I don't have a gpu

**Comment by DillFrescott** [comment]
Hmmmm, the issue seems to be unrelated to the gpu in that case. To be honest I just tried one of the other AI networks and it worked. I don't know enough about the program to diagnose further. Please let me know if you figure out why exactly it's throwing the error.

Perhaps try pinging the owner of the project.

**Comment by DillFrescott** [comment]
Sorry I wasn't very helpful.

**Comment by Flecser** [comment]
> Sorry I wasn't very helpful.

can you send me a screenshot of your whole window? so I can look if I changed anything by mistake

**Comment by Flecser** [comment]
@n00mkrad can you help me with this? I am running the latest version that is available, I have all the python things installed and its just giving me the 2 errors that dill posted above.

**Comment by DillFrescott** [comment]
I just download the default file and change the AI network and the output quality under settings to 100. I don't use the program much do I just re-download it when I need it. So besides those two things its completely stock.

Oh, and I check the use cpu mode box. Since my AMD GPU doesn't work well with the software from my knowledge.

**Comment by DillFrescott** [comment]
The best advice I can give is to temporarily disable your antivirus and put cupscale in a folder that you have full user permissions for such as `Downloads`. If it still doesn't work I have no idea.
