### ISSUE TITLE
Issues in 1.38 and 1.39

### ISSUE THREAD

**Issue by Kupo91** [n00mkrad/cupscale#86]
In the past I ran cupscale 1.37 but after updating to 1.38 or 1.39, the upscales look wrong.
I tried different models but same result.
I attached the original texture and upscales with 1.37, 1.38 and 1.39 so you can see the difference and test it yourself.

[texture upscales.zip](https://github.com/n00mkrad/cupscale/files/7357884/texture.upscales.zip)

**Comment by n00mkrad** [comment]
Try a different alpha mode in the settings.

![image](https://user-images.githubusercontent.com/61149547/137595570-d475c4ef-8b8a-41cb-9b03-1bb3e5b65699.png)

**Comment by Kupo91** [comment]
You're right in v1.37 I used mode 2 (separated alpha).
Using this setting in v1.39 fixed my issue.
Sorry and thanks for your fast reply :)
