### ISSUE TITLE
ESRGAN+ models don't work

### ISSUE THREAD

**Issue by AkitoFire** [n00mkrad/cupscale#93]
Hey,
I'm having trouble getting ESRGAN+ models to work - since Cupscale is based on Joey's fork I assume it's possible but I'm getting these errors:
`Upscaling...
1 preview.png.png
Image loaded
Reloading model - model_path: D:\OtherPrograms\Cupscale1.39.0f1\CupscaleData\models\2x_MangaScaleV3.pth - last_model: None
Setting last_model to D:\OtherPrograms\Cupscale1.39.0f1\CupscaleData\models\2x_MangaScaleV3.pth
Traceback (most recent call last):
  File "upscale.py", line 368, in <module>
    load_model(model_path)
  File "upscale.py", line 225, in load_model
    model.load_state_dict(state_dict, strict=True)
  File "D:\OtherPrograms\Cupscale1.39.0f1\CupscaleData\bin\py\Lib\site-packages\torch\nn\modules\module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for RRDB_Net:
        Unexpected key(s) in state_dict: "model.1.sub.0.RDB1.conv1x1.weight", "model.1.sub.0.RDB2.conv1x1.weight", "model.1.sub.0.RDB3.conv1x1.weight", "model.1.sub.1.RDB1.conv1x1.weight", "model.1.sub.1.RDB2.conv1x1.weight", "model.1.sub.1.RDB3.conv1x1.weight", "model.1.sub.2.RDB1.conv1x1.weight", "model.1.sub.2.RDB2.conv1x1.weight", "model.1.sub.2.RDB3.conv1x1.weight", "model.1.sub.3.RDB1.conv1x1.weight", "model.1.sub.3.RDB2.conv1x1.weight", "model.1.sub.3.RDB3.conv1x1.weight", "model.1.sub.4.RDB1.conv1x1.weight", "model.1.sub.4.RDB2.conv1x1.weight", "model.1.sub.4.RDB3.conv1x1.weight", "model.1.sub.5.RDB1.conv1x1.weight", "model.1.sub.5.RDB2.conv1x1.weight", "model.1.sub.5.RDB3.conv1x1.weight", "model.1.sub.6.RDB1.conv1x1.weight", "model.1.sub.6.RDB2.conv1x1.weight", "model.1.sub.6.RDB3.conv1x1.weight", "model.1.sub.7.RDB1.conv1x1.weight", "model.1.sub.7.RDB2.conv1x1.weight", "model.1.sub.7.RDB3.conv1x1.weight", "model.1.sub.8.RDB1.conv1x1.weight", "model.1.sub.8.RDB2.conv1x1.weight", "model.1.sub.8.RDB3.conv1x1.weight", "model.1.sub.9.RDB1.conv1x1.weight", "model.1.sub.9.RDB2.conv1x1.weight", "model.1.sub.9.RDB3.conv1x1.weight", "model.1.sub.10.RDB1.conv1x1.weight", "model.1.sub.10.RDB2.conv1x1.weight", "model.1.sub.10.RDB3.conv1x1.weight", "model.1.sub.11.RDB1.conv1x1.weight", "model.1.sub.11.RDB2.conv1x1.weight", "model.1.sub.11.RDB3.conv1x1.weight", "model.1.sub.12.RDB1.conv1x1.weight", "model.1.sub.12.RDB2.conv1x1.weight", "model.1.sub.12.RDB3.conv1x1.weight", "model.1.sub.13.RDB1.conv1x1.weight", "model.1.sub.13.RDB2.conv1x1.weight", "model.1.sub.13.RDB3.conv1x1.weight", "model.1.sub.14.RDB1.conv1x1.weight", "model.1.sub.14.RDB2.conv1x1.weight", "model.1.sub.14.RDB3.conv1x1.weight", "model.1.sub.15.RDB1.conv1x1.weight", "model.1.sub.15.RDB2.conv1x1.weight", "model.1.sub.15.RDB3.conv1x1.weight", "model.1.sub.16.RDB1.conv1x1.weight", "model.1.sub.16.RDB2.conv1x1.weight", "model.1.sub.16.RDB3.conv1x1.weight", "model.1.sub.17.RDB1.conv1x1.weight", "model.1.sub.17.RDB2.conv1x1.weight", "model.1.sub.17.RDB3.conv1x1.weight", "model.1.sub.18.RDB1.conv1x1.weight", "model.1.sub.18.RDB2.conv1x1.weight", "model.1.sub.18.RDB3.conv1x1.weight", "model.1.sub.19.RDB1.conv1x1.weight", "model.1.sub.19.RDB2.conv1x1.weight", "model.1.sub.19.RDB3.conv1x1.weight", "model.1.sub.20.RDB1.conv1x1.weight", "model.1.sub.20.RDB2.conv1x1.weight", "model.1.sub.20.RDB3.conv1x1.weight", "model.1.sub.21.RDB1.conv1x1.weight", "model.1.sub.21.RDB2.conv1x1.weight", "model.1.sub.21.RDB3.conv1x1.weight", "model.1.sub.22.RDB1.conv1x1.weight", "model.1.sub.22.RDB2.conv1x1.weight", "model.1.sub.22.RDB3.conv1x1.weight".`

I tested out all of the ESRGAN+ models listed on [this website here](https://upscale.wiki/wiki/Model_Database) and all of them gave me similar errors. 
Thanks in Advance!

**Comment by n00mkrad** [comment]
I have not yet updated the fork to support this, but it's on my todo list.

**Comment by n00mkrad** [comment]
Refer to https://github.com/n00mkrad/cupscale/pull/99

**Comment by GritYolo** [comment]
> Hey, I'm having trouble getting ESRGAN+ models to work - since Cupscale is based on Joey's fork I assume it's possible but I'm getting these errors: `Upscaling... 1 preview.png.png Image loaded Reloading model - model_path: D:\OtherPrograms\Cupscale1.39.0f1\CupscaleData\models\2x_MangaScaleV3.pth - last_model: None Setting last_model to D:\OtherPrograms\Cupscale1.39.0f1\CupscaleData\models\2x_MangaScaleV3.pth Traceback (most recent call last): File "upscale.py", line 368, in <module> load_model(model_path) File "upscale.py", line 225, in load_model model.load_state_dict(state_dict, strict=True) File "D:\OtherPrograms\Cupscale1.39.0f1\CupscaleData\bin\py\Lib\site-packages\torch\nn\modules\module.py", line 1044, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for RRDB_Net: Unexpected key(s) in state_dict: "model.1.sub.0.RDB1.conv1x1.weight", "model.1.sub.0.RDB2.conv1x1.weight", "model.1.sub.0.RDB3.conv1x1.weight", "model.1.sub.1.RDB1.conv1x1.weight", "model.1.sub.1.RDB2.conv1x1.weight", "model.1.sub.1.RDB3.conv1x1.weight", "model.1.sub.2.RDB1.conv1x1.weight", "model.1.sub.2.RDB2.conv1x1.weight", "model.1.sub.2.RDB3.conv1x1.weight", "model.1.sub.3.RDB1.conv1x1.weight", "model.1.sub.3.RDB2.conv1x1.weight", "model.1.sub.3.RDB3.conv1x1.weight", "model.1.sub.4.RDB1.conv1x1.weight", "model.1.sub.4.RDB2.conv1x1.weight", "model.1.sub.4.RDB3.conv1x1.weight", "model.1.sub.5.RDB1.conv1x1.weight", "model.1.sub.5.RDB2.conv1x1.weight", "model.1.sub.5.RDB3.conv1x1.weight", "model.1.sub.6.RDB1.conv1x1.weight", "model.1.sub.6.RDB2.conv1x1.weight", "model.1.sub.6.RDB3.conv1x1.weight", "model.1.sub.7.RDB1.conv1x1.weight", "model.1.sub.7.RDB2.conv1x1.weight", "model.1.sub.7.RDB3.conv1x1.weight", "model.1.sub.8.RDB1.conv1x1.weight", "model.1.sub.8.RDB2.conv1x1.weight", "model.1.sub.8.RDB3.conv1x1.weight", "model.1.sub.9.RDB1.conv1x1.weight", "model.1.sub.9.RDB2.conv1x1.weight", "model.1.sub.9.RDB3.conv1x1.weight", "model.1.sub.10.RDB1.conv1x1.weight", "model.1.sub.10.RDB2.conv1x1.weight", "model.1.sub.10.RDB3.conv1x1.weight", "model.1.sub.11.RDB1.conv1x1.weight", "model.1.sub.11.RDB2.conv1x1.weight", "model.1.sub.11.RDB3.conv1x1.weight", "model.1.sub.12.RDB1.conv1x1.weight", "model.1.sub.12.RDB2.conv1x1.weight", "model.1.sub.12.RDB3.conv1x1.weight", "model.1.sub.13.RDB1.conv1x1.weight", "model.1.sub.13.RDB2.conv1x1.weight", "model.1.sub.13.RDB3.conv1x1.weight", "model.1.sub.14.RDB1.conv1x1.weight", "model.1.sub.14.RDB2.conv1x1.weight", "model.1.sub.14.RDB3.conv1x1.weight", "model.1.sub.15.RDB1.conv1x1.weight", "model.1.sub.15.RDB2.conv1x1.weight", "model.1.sub.15.RDB3.conv1x1.weight", "model.1.sub.16.RDB1.conv1x1.weight", "model.1.sub.16.RDB2.conv1x1.weight", "model.1.sub.16.RDB3.conv1x1.weight", "model.1.sub.17.RDB1.conv1x1.weight", "model.1.sub.17.RDB2.conv1x1.weight", "model.1.sub.17.RDB3.conv1x1.weight", "model.1.sub.18.RDB1.conv1x1.weight", "model.1.sub.18.RDB2.conv1x1.weight", "model.1.sub.18.RDB3.conv1x1.weight", "model.1.sub.19.RDB1.conv1x1.weight", "model.1.sub.19.RDB2.conv1x1.weight", "model.1.sub.19.RDB3.conv1x1.weight", "model.1.sub.20.RDB1.conv1x1.weight", "model.1.sub.20.RDB2.conv1x1.weight", "model.1.sub.20.RDB3.conv1x1.weight", "model.1.sub.21.RDB1.conv1x1.weight", "model.1.sub.21.RDB2.conv1x1.weight", "model.1.sub.21.RDB3.conv1x1.weight", "model.1.sub.22.RDB1.conv1x1.weight", "model.1.sub.22.RDB2.conv1x1.weight", "model.1.sub.22.RDB3.conv1x1.weight".`
> 
> I tested out all of the ESRGAN+ models listed on [this website here](https://upscale.wiki/wiki/Model_Database) and all of them gave me similar errors. Thanks in Advance!

hello , i meet the problem too! i see the esrgan+ support,but i don't know how to use it.Could you give me a hand?
