### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by HackerDaGreat57** [n00mkrad/cupscale#94]
Hi there. I see you've made amazing progress towards great pieces of software (including Flowframes, that one's a masterpiece). I have just one question - Is it possible for these apps (also Flowframes) to run on an M1/Pro/Max chip and utilize their own special hardware?

I'm asking for help because I'm planning a switch to Mac after seeing that Windows 11 is still as slow and buggy as 10. The only thing I'm going to miss are UWP games and your astonishing software. Yes, I've tried Wine and Parallels. They just aren't the same as a native macOS application. (I know that because my VM is running just as fast as a physical Mac. The only thing that's off about it is the fact that there's no Bluetooth, which is essential).

**Comment by Katzenwerfer** [comment]
I haven't heard of the dev planning to port it any time soon (still wait for a final reply from him)
In the meantime you could try to run [ESRGAN](https://github.com/JoeyBallentine/ESRGAN) as CLI, but it might be a tad tedious to set up

**Comment by HackerDaGreat57** [comment]
I'll try in a VM. Since I'm just a hobbyist, I may be able to use my future physical Mac to help port it.

**Comment by HackerDaGreat57** [comment]
My VM suddenly just "stopped", it's as laggy as if it were running on a quarter of 1 thread. Idk, I guess I'll just have to use Parallels or something. I know I'm gonna have to buy it eventually, since I just bought Forza Horizon 5 and realized the bitter truth of its "cross-platformness".
